Auth0_login && dashboard
l3atbc/games-with-words-front-end pull request #6
Opened 2017-09-29 21:29 UTC by lbai001

autho0 login signup

user profile from auth0

basic profile display
add fontawsome

code clean up

Add forum link to dashboard navigation

remove general profile information from dashboard

recover rebase errors

switches login/dashboard in nav

2017-09-30 00:35 UTC, RobAWilkinson requested changes

2017-09-30 00:35 UTC, RobAWilkinson commented on components/DashboardNav/index.js
> +
Please remove if not needed 👌

2017-09-30 00:35 UTC, RobAWilkinson commented on components/DashboardNav/styles.css
> +  color: tomato;
match this with the color of the head on homepage

2017-09-30 00:35 UTC, RobAWilkinson commented on core/auth.js
> +    this.getProfile = this.getProfile.bind(this);
lets move these into static class properties so we don't overdose on `bind` `login = () => { }` etc...

2017-09-30 00:35 UTC, RobAWilkinson commented on core/auth.js
> +    browserHistory.push('/dashboard');
think about swapping with `replace` so the user doesn't go back to a page with no data upon logout

2017-09-30 00:35 UTC, RobAWilkinson commented on core/routes.js
> +    console.log('hello?!', nextState.location.hash);
please remove console log

2017-09-30 00:35 UTC, RobAWilkinson commented on pages/containers/container.css
> +.login_link {
dashes in css classes please `login-link`

2017-09-30 00:35 UTC, RobAWilkinson commented on core/auth.js
> +  }
please convert into promise rather than callback

2017-09-30 03:44 UTC, lbai001 commented on components/DashboardNav/index.js
> +
check

2017-09-30 03:44 UTC, lbai001 commented on components/DashboardNav/styles.css
> +  color: tomato;
check

2017-09-30 03:46 UTC, lbai001 commented on core/auth.js
> +    this.getProfile = this.getProfile.bind(this);
check

2017-09-30 04:26 UTC, lbai001 commented on core/auth.js
> +  }
check

2017-10-02 12:33 UTC, RobAWilkinson commented
LGTM 👍

2017-10-02 12:33 UTC, merged